//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier_Device
    {
        public int Cashier_ID { get; set; }
        public Nullable<byte> Device_Type { get; set; }
        public string Device_Token { get; set; }
    
        public virtual Cashier_Key Cashier_Key { get; set; }
    }
}
