//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier_Key
    {
        public int Cashier_ID { get; set; }
        public string API_Key { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    
        public virtual Cashier_Device Cashier_Device { get; set; }
        public virtual Cashier Cashier { get; set; }
    }
}
