//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Balance
    {
        public System.DateTime Balance_Date { get; set; }
        public int Cashier_ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<decimal> Opening_Value { get; set; }
        public Nullable<decimal> Closing_Value { get; set; }
        public string User_Created { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string User_Updated { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Cashier Cashier { get; set; }
    }
}
