//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_IN_Request_Items
    {
        public int Item_ID { get; set; }
        public Nullable<int> Request_ID { get; set; }
        public Nullable<int> Sub_Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Inventory_IN_Requests Inventory_IN_Requests { get; set; }
        public virtual Sub_Products Sub_Products { get; set; }
    }
}
