//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_IN_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_IN_Requests()
        {
            this.Inventory_IN_Request_Items = new HashSet<Inventory_IN_Request_Items>();
        }
    
        public int Request_ID { get; set; }
        public Nullable<int> Trader_ID { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<bool> Is_Completed { get; set; }
        public string User_Completed { get; set; }
        public Nullable<System.DateTime> Date_Completed { get; set; }
        public string Request_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_IN_Request_Items> Inventory_IN_Request_Items { get; set; }
        public virtual Trader Trader { get; set; }
    }
}
