//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageWord
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string English { get; set; }
        public string Arabic { get; set; }
        public bool IsActive { get; set; }
    }
}
