//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public Nullable<int> Trader_ID { get; set; }
        public Nullable<int> Bank_ID { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Details { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Is_Completed { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public string Payment_Ref { get; set; }
        public string User_Created { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string User_Updated { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Payment_Types Payment_Types { get; set; }
        public virtual Trader Trader { get; set; }
    }
}
