//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elaunch_posEntities : DbContext
    {
        public elaunch_posEntities()
            : base("name=elaunch_posEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Cashier_Device> Cashier_Device { get; set; }
        public virtual DbSet<Cashier_Key> Cashier_Key { get; set; }
        public virtual DbSet<Cashier> Cashiers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Daily_Balance> Daily_Balance { get; set; }
        public virtual DbSet<ID_Types> ID_Types { get; set; }
        public virtual DbSet<Inventory_In> Inventory_In { get; set; }
        public virtual DbSet<Inventory_IN_Request_Items> Inventory_IN_Request_Items { get; set; }
        public virtual DbSet<Inventory_IN_Requests> Inventory_IN_Requests { get; set; }
        public virtual DbSet<Inventory_Out> Inventory_Out { get; set; }
        public virtual DbSet<Inventory_Out_Reasons> Inventory_Out_Reasons { get; set; }
        public virtual DbSet<Inventory_Transfer_Items> Inventory_Transfer_Items { get; set; }
        public virtual DbSet<Inventory_Transfers> Inventory_Transfers { get; set; }
        public virtual DbSet<Invoice_Details> Invoice_Details { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LanguageWord> LanguageWords { get; set; }
        public virtual DbSet<Management_Discounts> Management_Discounts { get; set; }
        public virtual DbSet<Payment_Types> Payment_Types { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Product_Ratings> Product_Ratings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<Refund_Details> Refund_Details { get; set; }
        public virtual DbSet<Saving_Methods> Saving_Methods { get; set; }
        public virtual DbSet<Sub_Product_Branches> Sub_Product_Branches { get; set; }
        public virtual DbSet<Sub_Products> Sub_Products { get; set; }
        public virtual DbSet<System_Users> System_Users { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Trader> Traders { get; set; }
        public virtual DbSet<User_Types> User_Types { get; set; }
    }
}
