//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Sub_Products = new HashSet<Sub_Products>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Code { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Trader_ID { get; set; }
        public string Product_Name { get; set; }
        public byte[] Product_Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Saving_Method_ID { get; set; }
        public Nullable<int> Validity_Days { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Saving_Methods Saving_Methods { get; set; }
        public virtual Trader Trader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Products> Sub_Products { get; set; }
    }
}
