//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund_Details
    {
        public int Details_ID { get; set; }
        public Nullable<int> Refund_ID { get; set; }
        public Nullable<int> Sub_Product_ID { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> Refunded_Quantity { get; set; }
        public Nullable<decimal> Trader_Portion { get; set; }
        public Nullable<decimal> Company_Commission { get; set; }
        public Nullable<decimal> Management_Discount { get; set; }
        public Nullable<decimal> Product_Discount { get; set; }
        public Nullable<decimal> Net_Refunded { get; set; }
    
        public virtual Refund Refund { get; set; }
        public virtual Sub_Products Sub_Products { get; set; }
    }
}
