//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Product_Branches
    {
        public int Product_Branch_ID { get; set; }
        public int Branch_ID { get; set; }
        public int Sub_Product_ID { get; set; }
        public Nullable<int> Available_Amount { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Sub_Products Sub_Products { get; set; }
    }
}
