//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sub_Products()
        {
            this.Inventory_In = new HashSet<Inventory_In>();
            this.Inventory_IN_Request_Items = new HashSet<Inventory_IN_Request_Items>();
            this.Inventory_Out = new HashSet<Inventory_Out>();
            this.Invoice_Details = new HashSet<Invoice_Details>();
            this.Refund_Details = new HashSet<Refund_Details>();
            this.Sub_Product_Branches = new HashSet<Sub_Product_Branches>();
        }
    
        public int Sub_Product_ID { get; set; }
        public string Sub_Product_Code { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public byte[] Sub_Product_Image { get; set; }
        public string Sub_Product_Name { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Selling_Price { get; set; }
        public Nullable<decimal> Product_Discount { get; set; }
        public Nullable<short> Discount_Type { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<short> Commission_Type { get; set; }
        public Nullable<int> Available_Amount { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_In> Inventory_In { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_IN_Request_Items> Inventory_IN_Request_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Out> Inventory_Out { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refund_Details> Refund_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Product_Branches> Sub_Product_Branches { get; set; }
    }
}
