//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Users
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string Full_Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public string User_Created { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string User_Updated { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
    
        public virtual User_Types User_Types { get; set; }
    }
}
