//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int Tax_ID { get; set; }
        public Nullable<decimal> Tax_Percentage { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
