//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elaunch_POS_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trader()
        {
            this.Inventory_IN_Requests = new HashSet<Inventory_IN_Requests>();
            this.Payments = new HashSet<Payment>();
            this.Products = new HashSet<Product>();
        }
    
        public int Trader_ID { get; set; }
        public string Trader_Code { get; set; }
        public string Full_Name { get; set; }
        public string Date_Of_Birth { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Address { get; set; }
        public string National_ID { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public string Issue_Date { get; set; }
        public string Issue_Place { get; set; }
        public string Experiences { get; set; }
        public Nullable<int> Bank_ID { get; set; }
        public string IBAN { get; set; }
        public string Commercial_License_ID { get; set; }
        public string Bank_Account_Holder { get; set; }
        public string Store_Name { get; set; }
        public string Maarof { get; set; }
        public string Instegram { get; set; }
        public string Twitter { get; set; }
        public string Snapchat { get; set; }
        public string Facebook { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Contact_No { get; set; }
        public string Phone_No { get; set; }
        public Nullable<bool> Mobile_Verified { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> Email_Verified { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Password { get; set; }
        public string User_Updated { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
        public Nullable<bool> is_Registration_Completed { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual City City { get; set; }
        public virtual ID_Types ID_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_IN_Requests> Inventory_IN_Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
